name: Generate players.json and publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'    # diário às 06:00 UTC (ajuste se quiser)
  workflow_dispatch:      # permite executar manualmente pelo Actions UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests urllib3

      - name: Run generator script
        run: python scripts/generate_data.py

      - name: Commit generated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/players.json
          git commit -m "Update players.json" || echo "no changes to commit"
          git push
